### ISSUE TITLE
Query about kafka_node_id

### ISSUE THREAD

**Issue by sterd71** [dragomirr/ansible-role-kafka#1]
Hi,

In the documentation you've said the kafka_node_id variable is required, but the example ansible script doesn't set this variable.

How should kafka_node_id be used in the yml file?

Thanks

**Comment by dragomirr** [comment]
Hi @sterd71,

That part of readme could have clearer instructions, will update. I did not set `kafka_node_id` in example as I have set that in inventory. 
 If you plan to have 1 kafka node you can set `kafka_node_id: 1`  in that file or file you have created and that's it.
If you have more than 1 node you need to set `kafka_node_id` for every host in your inventory.

https://github.com/dragomirr/ansible-role-kafka/blob/main/molecule/cluster/molecule.yml
This is test case for the role and as you can see in `provisioner` segment every node has `kafka_node_id` set.

**Comment by sterd71** [comment]
Thanks for getting back to me.  All sorted now.
