### ISSUE TITLE
Cannot change server.properties

### ISSUE THREAD

**Issue by HirossxD** [dragomirr/ansible-role-kafka#2]
After adding lines into templates/server.properties.j2 cluster is deployed with defaults.
when change in .ansible is made, playbook fails on 
```
TASK [dragomirr.kafka : Wait for Kafka controllers to start]
Timeout when waiting for 127.0.0.1:9092
```

same with kafka version, change in defaults/main.yml is not working.

so how to configure this galaxy role ?

**Comment by dragomirr** [comment]
Depending on how many nodes you have.
If you have only one example playbook will work. If you have more then one you need to create inventory and specify `kafka_node_id` for every node  and possible `kafka_node_ip` depending on the setup.
Something like this:
```bash
[servers]
kafka.node.one.ip kafka_node_id=0
kafka.node.two.ip kafka_node_id=1
kafka.node.three.ip kafka_node_id=2
```
Regarding version change, with version change it is required to update `kafka_checksum` varaible. You can find correct checksum on the kafka download page https://kafka.apache.org/downloads . When you select the version you like there is `sha512`  link and it will show you the page with correct sha.

**Comment by dragomirr** [comment]
You can get idea how to configure your inventory [here](https://github.com/dragomirr/ansible-role-kafka/blob/main/molecule/cluster/molecule.yml) . Check provisioner section inventory.

**Comment by HirossxD** [comment]
Hello, sorry for late reply, the issue was in the config itself. I thought its an ansible issue.

after adding lines in server.properties with cruise_control configuration, brokers will stop listening on ports.
```
metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
cruise.control.metrics.topic.auto.create=true
cruise.control.metrics.topic.num.partitions=1
cruise.control.metrics.topic.replication.factor=1
```
not sure why exactly, i will need to investigate it further.

However thank you for the response
I am closing this issue as the root cause has no origin in ansible.
