### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by punit-kulal** [dragomirr/ansible-role-kafka#3]
Can we add support for KAFKA_OPTS for additional jmx options which could be provided as an env variable.
Example : `KAFKA_OPTS="-javaagent:/opt/jmx_exporter.jar=8080:/opt/jmx_exporter_config.yml"` can be added to a metric exporter.

Can raise a pull request for the same if required.

**Comment by dragomirr** [comment]
Hi,

That will be nice improvement, I'll add it during the day tomorrow.

**Comment by dragomirr** [comment]
Added version 0.4.0 which has `kafka_opts` variable which you can use to define custom options. It can be list or string.

Check it out.
